import uuid
from django.db import models

class Track(models.Model):
    """
    Represents a unique song.
    Acts as the central entity for descriptive metadata.
    """
    # This is the unique identifier for the track in the database
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # This is the unique identifier for the track in the Spotify API
    spotify_id = models.CharField(max_length=255, unique=True, db_index=True)
    
    title = models.CharField(max_length=255)
    artist_name = models.CharField(max_length=255)
    album_name = models.CharField(max_length=255)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Track"
        verbose_name_plural = "Tracks"

    def __str__(self):
        return f"{self.title} - {self.artist_name}"

class AudioFeatures(models.Model):
    """
    Contains raw numerical audio data (0.0 - 1.0) for the ML model.
    1:1 relationship with Track (A track can have only one set of audio features).
    """
    track = models.OneToOneField(Track, on_delete=models.CASCADE, related_name='features')
    
    danceability = models.FloatField()
    energy = models.FloatField()
    valence = models.FloatField()
    acousticness = models.FloatField()
    tempo = models.FloatField()
    
    # Additional useful fields from dataset/API with default values
    instrumentalness = models.FloatField(default=0.0)
    liveness = models.FloatField(default=0.0)
    loudness = models.FloatField(default=0.0)
    speechiness = models.FloatField(default=0.0)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Audio Feature"
        verbose_name_plural = "Audio Features"

    def __str__(self):
        return f"Features for {self.track.title}"

class UserArchetype(models.Model):
    """
    Defines pre-calculated profiles (Clusters) for simulation.
    """
    name = models.SlugField(unique=True) # e.g., 'the-high-intensity'
    display_name = models.CharField(max_length=100)
    description = models.TextField()
    
    # Value ranges to filter tracks matching this archetype
    min_values = models.JSONField(help_text="Dictionary of minimum values (e.g., {'energy': 0.8})")
    max_values = models.JSONField(help_text="Dictionary of maximum values")
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "User Archetype"
        verbose_name_plural = "User Archetypes"

    def __str__(self):
        return self.display_name

class UserProfile(models.Model):
    """
    Represents the end user (simulated or real).
    Links a user ID with their history and archetype.
    """
    spotify_id = models.CharField(max_length=255, unique=True, db_index=True)
    display_name = models.CharField(max_length=255)
    
    # Archetype assigned in simulation (can be null if it's a new real user). 
    # One to many relationship with UserArchetype.
    archetype = models.ForeignKey(UserArchetype, on_delete=models.SET_NULL, null=True, blank=True)
    
    # Listening history (simulated or real)
    tracks = models.ManyToManyField(Track, related_name='listeners', blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "User Profile"
        verbose_name_plural = "User Profiles"

    def __str__(self):
        return self.display_name

class UserInsight(models.Model):
    """
    Stores reports generated by a LLM.
    """
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='insights')
    personality_label = models.CharField(max_length=255)
    llm_response = models.TextField()
    
    # this data allows us to generate the charts in the dashboard without having to re-run the ML model
    cluster_centers = models.JSONField(help_text="Centroid data for charts")
    
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "User Insight"
        verbose_name_plural = "User Insights"

    def __str__(self):
        return f"Insight for {self.user.display_name} ({self.created_at.date()})"
